openapi: 3.0.3
info:
  title: Evolution of Todo - Authentication API
  version: 1.0.0
  description: User authentication endpoints for Phase II

servers:
  - url: /api/auth
    description: Authentication API base path

paths:
  /signup:
    post:
      summary: Register a new user account
      description: Creates a new user account with email and password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref:chemas/ErrorResponse'
        '409 '#/components/s':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /signin:
    post:
      summary: Authenticate and sign in
      description: Authenticates user with email and password, returns session
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SigninRequest'
      responses:
        '200':
          description: Authentication successful
          headers:
            Set-Cookie:
              description: Session cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SigninResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /signout:
    post:
      summary: Sign out current user
      description: Ends the current session
      tags:
        - Authentication
      responses:
        '200':
          description: Signed out successfully
          headers:
            Set-Cookie:
              description: Clears session cookie
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignoutResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /me:
    get:
      summary: Get current user
      description: Returns information about the currently authenticated user
      tags:
        - Authentication
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
          description: User's email address
        password:
          type: string
          minLength: 8
          maxLength: 128
          example: securepassword123
          description: User's password (min 8 characters)

    SignupResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Account created successfully. Please sign in.

    SigninRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: securepassword123

    SigninResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        user:
          type: object
          properties:
            id:
              type: integer
              example: 1
            email:
              type: string
              example: user@example.com

    SignoutResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: Signed out successfully

    MeResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: integer
              example: 1
            email:
              type: string
              example: user@example.com
            created_at:
              type: string
              format: date-time
              example: '2026-01-04T10:00:00Z'

    ErrorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: VALIDATION_ERROR
            message:
              type: string
              example: Please enter a valid email address

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: auth_session
